# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: building_zone_names.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='building_zone_names.proto',
  package='building_zone_names',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x19\x62uilding_zone_names.proto\x12\x13\x62uilding_zone_names\"\x11\n\x0f\x42uildingRequest\"\x1f\n\x0bZoneRequest\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\"\x19\n\tNamePoint\x12\x0c\n\x04name\x18\x01 \x01(\t\"6\n\x05Reply\x12-\n\x05names\x18\x01 \x03(\x0b\x32\x1e.building_zone_names.NamePoint2\xb3\x01\n\x11\x42uildingZoneNames\x12R\n\x0cGetBuildings\x12$.building_zone_names.BuildingRequest\x1a\x1a.building_zone_names.Reply\"\x00\x12J\n\x08GetZones\x12 .building_zone_names.ZoneRequest\x1a\x1a.building_zone_names.Reply\"\x00\x42\x02P\x01\x62\x06proto3')
)




_BUILDINGREQUEST = _descriptor.Descriptor(
  name='BuildingRequest',
  full_name='building_zone_names.BuildingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=67,
)


_ZONEREQUEST = _descriptor.Descriptor(
  name='ZoneRequest',
  full_name='building_zone_names.ZoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='building_zone_names.ZoneRequest.building', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=100,
)


_NAMEPOINT = _descriptor.Descriptor(
  name='NamePoint',
  full_name='building_zone_names.NamePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='building_zone_names.NamePoint.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=127,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='building_zone_names.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='building_zone_names.Reply.names', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=183,
)

_REPLY.fields_by_name['names'].message_type = _NAMEPOINT
DESCRIPTOR.message_types_by_name['BuildingRequest'] = _BUILDINGREQUEST
DESCRIPTOR.message_types_by_name['ZoneRequest'] = _ZONEREQUEST
DESCRIPTOR.message_types_by_name['NamePoint'] = _NAMEPOINT
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildingRequest = _reflection.GeneratedProtocolMessageType('BuildingRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUILDINGREQUEST,
  __module__ = 'building_zone_names_pb2'
  # @@protoc_insertion_point(class_scope:building_zone_names.BuildingRequest)
  ))
_sym_db.RegisterMessage(BuildingRequest)

ZoneRequest = _reflection.GeneratedProtocolMessageType('ZoneRequest', (_message.Message,), dict(
  DESCRIPTOR = _ZONEREQUEST,
  __module__ = 'building_zone_names_pb2'
  # @@protoc_insertion_point(class_scope:building_zone_names.ZoneRequest)
  ))
_sym_db.RegisterMessage(ZoneRequest)

NamePoint = _reflection.GeneratedProtocolMessageType('NamePoint', (_message.Message,), dict(
  DESCRIPTOR = _NAMEPOINT,
  __module__ = 'building_zone_names_pb2'
  # @@protoc_insertion_point(class_scope:building_zone_names.NamePoint)
  ))
_sym_db.RegisterMessage(NamePoint)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'building_zone_names_pb2'
  # @@protoc_insertion_point(class_scope:building_zone_names.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_BUILDINGZONENAMES = _descriptor.ServiceDescriptor(
  name='BuildingZoneNames',
  full_name='building_zone_names.BuildingZoneNames',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=186,
  serialized_end=365,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBuildings',
    full_name='building_zone_names.BuildingZoneNames.GetBuildings',
    index=0,
    containing_service=None,
    input_type=_BUILDINGREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetZones',
    full_name='building_zone_names.BuildingZoneNames.GetZones',
    index=1,
    containing_service=None,
    input_type=_ZONEREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUILDINGZONENAMES)

DESCRIPTOR.services_by_name['BuildingZoneNames'] = _BUILDINGZONENAMES

# @@protoc_insertion_point(module_scope)
