# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='price.proto',
  package='price',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x0bprice.proto\x12\x05price\"G\n\nPricePoint\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x0e\n\x06window\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"(\n\x15\x44\x65mandResponseRequest\x12\x0f\n\x07utility\x18\x01 \x01(\t\"C\n\x13\x44\x65mandResponseReply\x12,\n\x08statuses\x18\x01 \x03(\x0b\x32\x1a.price.DemandResponsePoint\"3\n\x13\x44\x65mandResponsePoint\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\x03\"#\n\x0f\x42uildingRequest\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\"o\n\x0cPriceRequest\x12\x0f\n\x07utility\x18\x01 \x01(\t\x12\x0e\n\x06tariff\x18\x02 \x01(\t\x12\x12\n\nprice_type\x18\x03 \x01(\t\x12\r\n\x05start\x18\x04 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x03\x12\x0e\n\x06window\x18\x06 \x01(\t\"M\n\x15\x41llTariffUtilityReply\x12\x34\n\x11tariffs_utilities\x18\x01 \x03(\x0b\x32\x19.price.TariffUtilityReply\"5\n\x12TariffUtilityReply\x12\x0f\n\x07utility\x18\x01 \x01(\t\x12\x0e\n\x06tariff\x18\x02 \x01(\t2\x89\x03\n\x05Price\x12\x36\n\x08GetPrice\x12\x13.price.PriceRequest\x1a\x11.price.PricePoint\"\x00\x30\x01\x12I\n\x19GetAllTariffsAndUtilities\x12\x0c.price.Empty\x1a\x1c.price.AllTariffUtilityReply\"\x00\x12J\n\x13GetTariffAndUtility\x12\x16.price.BuildingRequest\x1a\x19.price.TariffUtilityReply\"\x00\x12W\n\x19GetDemandResponseForecast\x12\x1c.price.DemandResponseRequest\x1a\x1a.price.DemandResponseReply\"\x00\x12X\n\x1aGetDemandResponseConfirmed\x12\x1c.price.DemandResponseRequest\x1a\x1a.price.DemandResponseReply\"\x00\x42\x02P\x01\x62\x06proto3')
)




_PRICEPOINT = _descriptor.Descriptor(
  name='PricePoint',
  full_name='price.PricePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='price.PricePoint.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='price.PricePoint.price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='price.PricePoint.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='price.PricePoint.window', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=93,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='price.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=102,
)


_DEMANDRESPONSEREQUEST = _descriptor.Descriptor(
  name='DemandResponseRequest',
  full_name='price.DemandResponseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utility', full_name='price.DemandResponseRequest.utility', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=144,
)


_DEMANDRESPONSEREPLY = _descriptor.Descriptor(
  name='DemandResponseReply',
  full_name='price.DemandResponseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuses', full_name='price.DemandResponseReply.statuses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=213,
)


_DEMANDRESPONSEPOINT = _descriptor.Descriptor(
  name='DemandResponsePoint',
  full_name='price.DemandResponsePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='price.DemandResponsePoint.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='price.DemandResponsePoint.status', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=266,
)


_BUILDINGREQUEST = _descriptor.Descriptor(
  name='BuildingRequest',
  full_name='price.BuildingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='price.BuildingRequest.building', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=303,
)


_PRICEREQUEST = _descriptor.Descriptor(
  name='PriceRequest',
  full_name='price.PriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utility', full_name='price.PriceRequest.utility', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariff', full_name='price.PriceRequest.tariff', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_type', full_name='price.PriceRequest.price_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='price.PriceRequest.start', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='price.PriceRequest.end', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='price.PriceRequest.window', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=416,
)


_ALLTARIFFUTILITYREPLY = _descriptor.Descriptor(
  name='AllTariffUtilityReply',
  full_name='price.AllTariffUtilityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tariffs_utilities', full_name='price.AllTariffUtilityReply.tariffs_utilities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=495,
)


_TARIFFUTILITYREPLY = _descriptor.Descriptor(
  name='TariffUtilityReply',
  full_name='price.TariffUtilityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utility', full_name='price.TariffUtilityReply.utility', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariff', full_name='price.TariffUtilityReply.tariff', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=550,
)

_DEMANDRESPONSEREPLY.fields_by_name['statuses'].message_type = _DEMANDRESPONSEPOINT
_ALLTARIFFUTILITYREPLY.fields_by_name['tariffs_utilities'].message_type = _TARIFFUTILITYREPLY
DESCRIPTOR.message_types_by_name['PricePoint'] = _PRICEPOINT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['DemandResponseRequest'] = _DEMANDRESPONSEREQUEST
DESCRIPTOR.message_types_by_name['DemandResponseReply'] = _DEMANDRESPONSEREPLY
DESCRIPTOR.message_types_by_name['DemandResponsePoint'] = _DEMANDRESPONSEPOINT
DESCRIPTOR.message_types_by_name['BuildingRequest'] = _BUILDINGREQUEST
DESCRIPTOR.message_types_by_name['PriceRequest'] = _PRICEREQUEST
DESCRIPTOR.message_types_by_name['AllTariffUtilityReply'] = _ALLTARIFFUTILITYREPLY
DESCRIPTOR.message_types_by_name['TariffUtilityReply'] = _TARIFFUTILITYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PricePoint = _reflection.GeneratedProtocolMessageType('PricePoint', (_message.Message,), dict(
  DESCRIPTOR = _PRICEPOINT,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.PricePoint)
  ))
_sym_db.RegisterMessage(PricePoint)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.Empty)
  ))
_sym_db.RegisterMessage(Empty)

DemandResponseRequest = _reflection.GeneratedProtocolMessageType('DemandResponseRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEMANDRESPONSEREQUEST,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.DemandResponseRequest)
  ))
_sym_db.RegisterMessage(DemandResponseRequest)

DemandResponseReply = _reflection.GeneratedProtocolMessageType('DemandResponseReply', (_message.Message,), dict(
  DESCRIPTOR = _DEMANDRESPONSEREPLY,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.DemandResponseReply)
  ))
_sym_db.RegisterMessage(DemandResponseReply)

DemandResponsePoint = _reflection.GeneratedProtocolMessageType('DemandResponsePoint', (_message.Message,), dict(
  DESCRIPTOR = _DEMANDRESPONSEPOINT,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.DemandResponsePoint)
  ))
_sym_db.RegisterMessage(DemandResponsePoint)

BuildingRequest = _reflection.GeneratedProtocolMessageType('BuildingRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUILDINGREQUEST,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.BuildingRequest)
  ))
_sym_db.RegisterMessage(BuildingRequest)

PriceRequest = _reflection.GeneratedProtocolMessageType('PriceRequest', (_message.Message,), dict(
  DESCRIPTOR = _PRICEREQUEST,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.PriceRequest)
  ))
_sym_db.RegisterMessage(PriceRequest)

AllTariffUtilityReply = _reflection.GeneratedProtocolMessageType('AllTariffUtilityReply', (_message.Message,), dict(
  DESCRIPTOR = _ALLTARIFFUTILITYREPLY,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.AllTariffUtilityReply)
  ))
_sym_db.RegisterMessage(AllTariffUtilityReply)

TariffUtilityReply = _reflection.GeneratedProtocolMessageType('TariffUtilityReply', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFUTILITYREPLY,
  __module__ = 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.TariffUtilityReply)
  ))
_sym_db.RegisterMessage(TariffUtilityReply)


DESCRIPTOR._options = None

_PRICE = _descriptor.ServiceDescriptor(
  name='Price',
  full_name='price.Price',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=553,
  serialized_end=946,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrice',
    full_name='price.Price.GetPrice',
    index=0,
    containing_service=None,
    input_type=_PRICEREQUEST,
    output_type=_PRICEPOINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllTariffsAndUtilities',
    full_name='price.Price.GetAllTariffsAndUtilities',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ALLTARIFFUTILITYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTariffAndUtility',
    full_name='price.Price.GetTariffAndUtility',
    index=2,
    containing_service=None,
    input_type=_BUILDINGREQUEST,
    output_type=_TARIFFUTILITYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDemandResponseForecast',
    full_name='price.Price.GetDemandResponseForecast',
    index=3,
    containing_service=None,
    input_type=_DEMANDRESPONSEREQUEST,
    output_type=_DEMANDRESPONSEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDemandResponseConfirmed',
    full_name='price.Price.GetDemandResponseConfirmed',
    index=4,
    containing_service=None,
    input_type=_DEMANDRESPONSEREQUEST,
    output_type=_DEMANDRESPONSEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRICE)

DESCRIPTOR.services_by_name['Price'] = _PRICE

# @@protoc_insertion_point(module_scope)
