# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter_data_historical.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meter_data_historical.proto',
  package='meter_data_historical',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bmeter_data_historical.proto\x12\x15meter_data_historical\"n\n\x07Request\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x03\x12\x12\n\npoint_type\x18\x04 \x01(\t\x12\x11\n\taggregate\x18\x05 \x01(\t\x12\x0e\n\x06window\x18\x06 \x01(\t\"-\n\x0eMeterDataPoint\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\r\n\x05power\x18\x02 \x01(\x01\"=\n\x05Reply\x12\x34\n\x05point\x18\x01 \x03(\x0b\x32%.meter_data_historical.MeterDataPoint2o\n\x13MeterDataHistorical\x12X\n\x16GetMeterDataHistorical\x12\x1e.meter_data_historical.Request\x1a\x1c.meter_data_historical.Reply\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='meter_data_historical.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='meter_data_historical.Request.building', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='meter_data_historical.Request.start', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='meter_data_historical.Request.end', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point_type', full_name='meter_data_historical.Request.point_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggregate', full_name='meter_data_historical.Request.aggregate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='meter_data_historical.Request.window', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=164,
)


_METERDATAPOINT = _descriptor.Descriptor(
  name='MeterDataPoint',
  full_name='meter_data_historical.MeterDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='meter_data_historical.MeterDataPoint.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='meter_data_historical.MeterDataPoint.power', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=211,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='meter_data_historical.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='meter_data_historical.Reply.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=274,
)

_REPLY.fields_by_name['point'].message_type = _METERDATAPOINT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['MeterDataPoint'] = _METERDATAPOINT
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'meter_data_historical_pb2'
  # @@protoc_insertion_point(class_scope:meter_data_historical.Request)
  ))
_sym_db.RegisterMessage(Request)

MeterDataPoint = _reflection.GeneratedProtocolMessageType('MeterDataPoint', (_message.Message,), dict(
  DESCRIPTOR = _METERDATAPOINT,
  __module__ = 'meter_data_historical_pb2'
  # @@protoc_insertion_point(class_scope:meter_data_historical.MeterDataPoint)
  ))
_sym_db.RegisterMessage(MeterDataPoint)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'meter_data_historical_pb2'
  # @@protoc_insertion_point(class_scope:meter_data_historical.Reply)
  ))
_sym_db.RegisterMessage(Reply)



_METERDATAHISTORICAL = _descriptor.ServiceDescriptor(
  name='MeterDataHistorical',
  full_name='meter_data_historical.MeterDataHistorical',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=276,
  serialized_end=387,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMeterDataHistorical',
    full_name='meter_data_historical.MeterDataHistorical.GetMeterDataHistorical',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERDATAHISTORICAL)

DESCRIPTOR.services_by_name['MeterDataHistorical'] = _METERDATAHISTORICAL

# @@protoc_insertion_point(module_scope)
