# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MeterDataHistorical_pb2 as MeterDataHistorical__pb2


class MeterDataHistoricalStub(object):
  """RPC definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMeterDataHistorical = channel.unary_unary(
        '/meter_data_historical.MeterDataHistorical/GetMeterDataHistorical',
        request_serializer=MeterDataHistorical__pb2.Request.SerializeToString,
        response_deserializer=MeterDataHistorical__pb2.Reply.FromString,
        )


class MeterDataHistoricalServicer(object):
  """RPC definition.
  """

  def GetMeterDataHistorical(self, request, context):
    """A simple RPC.
    An error is returned if there is no meter data for the given request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MeterDataHistoricalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMeterDataHistorical': grpc.unary_unary_rpc_method_handler(
          servicer.GetMeterDataHistorical,
          request_deserializer=MeterDataHistorical__pb2.Request.FromString,
          response_serializer=MeterDataHistorical__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'meter_data_historical.MeterDataHistorical', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
