# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import temperature_bands_pb2 as temperature__bands__pb2


class SchedulesStub(object):
  """The temperature bands service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetComfortband = channel.unary_stream(
        '/temperature_bands.Schedules/GetComfortband',
        request_serializer=temperature__bands__pb2.ScheduleRequest.SerializeToString,
        response_deserializer=temperature__bands__pb2.SchedulePoint.FromString,
        )
    self.GetDoNotExceed = channel.unary_stream(
        '/temperature_bands.Schedules/GetDoNotExceed',
        request_serializer=temperature__bands__pb2.ScheduleRequest.SerializeToString,
        response_deserializer=temperature__bands__pb2.SchedulePoint.FromString,
        )


class SchedulesServicer(object):
  """The temperature bands service definition.
  """

  def GetComfortband(self, request, context):
    """A simple RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDoNotExceed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SchedulesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetComfortband': grpc.unary_stream_rpc_method_handler(
          servicer.GetComfortband,
          request_deserializer=temperature__bands__pb2.ScheduleRequest.FromString,
          response_serializer=temperature__bands__pb2.SchedulePoint.SerializeToString,
      ),
      'GetDoNotExceed': grpc.unary_stream_rpc_method_handler(
          servicer.GetDoNotExceed,
          request_deserializer=temperature__bands__pb2.ScheduleRequest.FromString,
          response_serializer=temperature__bands__pb2.SchedulePoint.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'temperature_bands.Schedules', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
