# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outdoor_temperature_historical.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='outdoor_temperature_historical.proto',
  package='outdoor_temperature_historical',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n$outdoor_temperature_historical.proto\x12\x1eoutdoor_temperature_historical\"C\n\x10TemperaturePoint\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\"e\n\x12TemperatureRequest\x12\x10\n\x08\x62uilding\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x03\x12\x0e\n\x06window\x18\x04 \x01(\t\x12\x11\n\taggregate\x18\x05 \x01(\t2\x9c\x02\n\x12OutdoorTemperature\x12\x86\x01\n\x1aGetPreprocessedTemperature\x12\x32.outdoor_temperature_historical.TemperatureRequest\x1a\x30.outdoor_temperature_historical.TemperaturePoint\"\x00\x30\x01\x12}\n\x11GetRawTemperature\x12\x32.outdoor_temperature_historical.TemperatureRequest\x1a\x30.outdoor_temperature_historical.TemperaturePoint\"\x00\x30\x01\x42\x02P\x01\x62\x06proto3')
)




_TEMPERATUREPOINT = _descriptor.Descriptor(
  name='TemperaturePoint',
  full_name='outdoor_temperature_historical.TemperaturePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='outdoor_temperature_historical.TemperaturePoint.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='outdoor_temperature_historical.TemperaturePoint.temperature', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='outdoor_temperature_historical.TemperaturePoint.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=139,
)


_TEMPERATUREREQUEST = _descriptor.Descriptor(
  name='TemperatureRequest',
  full_name='outdoor_temperature_historical.TemperatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='outdoor_temperature_historical.TemperatureRequest.building', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='outdoor_temperature_historical.TemperatureRequest.start', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='outdoor_temperature_historical.TemperatureRequest.end', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='outdoor_temperature_historical.TemperatureRequest.window', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggregate', full_name='outdoor_temperature_historical.TemperatureRequest.aggregate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['TemperaturePoint'] = _TEMPERATUREPOINT
DESCRIPTOR.message_types_by_name['TemperatureRequest'] = _TEMPERATUREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperaturePoint = _reflection.GeneratedProtocolMessageType('TemperaturePoint', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATUREPOINT,
  __module__ = 'outdoor_temperature_historical_pb2'
  # @@protoc_insertion_point(class_scope:outdoor_temperature_historical.TemperaturePoint)
  ))
_sym_db.RegisterMessage(TemperaturePoint)

TemperatureRequest = _reflection.GeneratedProtocolMessageType('TemperatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATUREREQUEST,
  __module__ = 'outdoor_temperature_historical_pb2'
  # @@protoc_insertion_point(class_scope:outdoor_temperature_historical.TemperatureRequest)
  ))
_sym_db.RegisterMessage(TemperatureRequest)


DESCRIPTOR._options = None

_OUTDOORTEMPERATURE = _descriptor.ServiceDescriptor(
  name='OutdoorTemperature',
  full_name='outdoor_temperature_historical.OutdoorTemperature',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=245,
  serialized_end=529,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPreprocessedTemperature',
    full_name='outdoor_temperature_historical.OutdoorTemperature.GetPreprocessedTemperature',
    index=0,
    containing_service=None,
    input_type=_TEMPERATUREREQUEST,
    output_type=_TEMPERATUREPOINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRawTemperature',
    full_name='outdoor_temperature_historical.OutdoorTemperature.GetRawTemperature',
    index=1,
    containing_service=None,
    input_type=_TEMPERATUREREQUEST,
    output_type=_TEMPERATUREPOINT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUTDOORTEMPERATURE)

DESCRIPTOR.services_by_name['OutdoorTemperature'] = _OUTDOORTEMPERATURE

# @@protoc_insertion_point(module_scope)
