# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import indoor_data_historical_pb2 as indoor__data__historical__pb2


class IndoorDataHistoricalStub(object):
  """The temperature service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRawTemperatures = channel.unary_stream(
        '/indoor_data_historical.IndoorDataHistorical/GetRawTemperatures',
        request_serializer=indoor__data__historical__pb2.Request.SerializeToString,
        response_deserializer=indoor__data__historical__pb2.TemperaturePoint.FromString,
        )
    self.GetRawActions = channel.unary_stream(
        '/indoor_data_historical.IndoorDataHistorical/GetRawActions',
        request_serializer=indoor__data__historical__pb2.Request.SerializeToString,
        response_deserializer=indoor__data__historical__pb2.ActionPoint.FromString,
        )
    self.GetRawTemperatureBands = channel.unary_stream(
        '/indoor_data_historical.IndoorDataHistorical/GetRawTemperatureBands',
        request_serializer=indoor__data__historical__pb2.Request.SerializeToString,
        response_deserializer=indoor__data__historical__pb2.Setpoint.FromString,
        )


class IndoorDataHistoricalServicer(object):
  """The temperature service definition.
  """

  def GetRawTemperatures(self, request, context):
    """A simple RPC.

    Sends the outside temperature for a given building, within a duration (start, end), and a requested window
    An error  is returned if there are no temperature for the given request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRawActions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRawTemperatureBands(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IndoorDataHistoricalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRawTemperatures': grpc.unary_stream_rpc_method_handler(
          servicer.GetRawTemperatures,
          request_deserializer=indoor__data__historical__pb2.Request.FromString,
          response_serializer=indoor__data__historical__pb2.TemperaturePoint.SerializeToString,
      ),
      'GetRawActions': grpc.unary_stream_rpc_method_handler(
          servicer.GetRawActions,
          request_deserializer=indoor__data__historical__pb2.Request.FromString,
          response_serializer=indoor__data__historical__pb2.ActionPoint.SerializeToString,
      ),
      'GetRawTemperatureBands': grpc.unary_stream_rpc_method_handler(
          servicer.GetRawTemperatureBands,
          request_deserializer=indoor__data__historical__pb2.Request.FromString,
          response_serializer=indoor__data__historical__pb2.Setpoint.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'indoor_data_historical.IndoorDataHistorical', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
