# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import baseline_optimizer_pb2 as baseline__optimizer__pb2


class BaselineOptimizerStub(object):
  """The controller service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNormalScheduleAction = channel.unary_unary(
        '/baseline_optimizer.BaselineOptimizer/GetNormalScheduleAction',
        request_serializer=baseline__optimizer__pb2.NormalScheduleRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )
    self.GetSetpointExpansionAction = channel.unary_unary(
        '/baseline_optimizer.BaselineOptimizer/GetSetpointExpansionAction',
        request_serializer=baseline__optimizer__pb2.SetpointExpansionRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )
    self.GetDemandChargeAction = channel.unary_unary(
        '/baseline_optimizer.BaselineOptimizer/GetDemandChargeAction',
        request_serializer=baseline__optimizer__pb2.DemandChargeRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )
    self.GetNormalScheduleSimulation = channel.unary_stream(
        '/baseline_optimizer.BaselineOptimizer/GetNormalScheduleSimulation',
        request_serializer=baseline__optimizer__pb2.NormalScheduleRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )
    self.GetSetpointExpansionSimulation = channel.unary_stream(
        '/baseline_optimizer.BaselineOptimizer/GetSetpointExpansionSimulation',
        request_serializer=baseline__optimizer__pb2.SetpointExpansionRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )
    self.GetDemandChargeSimualtion = channel.unary_stream(
        '/baseline_optimizer.BaselineOptimizer/GetDemandChargeSimualtion',
        request_serializer=baseline__optimizer__pb2.DemandChargeRequest.SerializeToString,
        response_deserializer=baseline__optimizer__pb2.Reply.FromString,
        )


class BaselineOptimizerServicer(object):
  """The controller service definition
  """

  def GetNormalScheduleAction(self, request, context):
    """A simple RPC.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSetpointExpansionAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDemandChargeAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNormalScheduleSimulation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSetpointExpansionSimulation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDemandChargeSimualtion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BaselineOptimizerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNormalScheduleAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetNormalScheduleAction,
          request_deserializer=baseline__optimizer__pb2.NormalScheduleRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
      'GetSetpointExpansionAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetSetpointExpansionAction,
          request_deserializer=baseline__optimizer__pb2.SetpointExpansionRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
      'GetDemandChargeAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetDemandChargeAction,
          request_deserializer=baseline__optimizer__pb2.DemandChargeRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
      'GetNormalScheduleSimulation': grpc.unary_stream_rpc_method_handler(
          servicer.GetNormalScheduleSimulation,
          request_deserializer=baseline__optimizer__pb2.NormalScheduleRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
      'GetSetpointExpansionSimulation': grpc.unary_stream_rpc_method_handler(
          servicer.GetSetpointExpansionSimulation,
          request_deserializer=baseline__optimizer__pb2.SetpointExpansionRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
      'GetDemandChargeSimualtion': grpc.unary_stream_rpc_method_handler(
          servicer.GetDemandChargeSimualtion,
          request_deserializer=baseline__optimizer__pb2.DemandChargeRequest.FromString,
          response_serializer=baseline__optimizer__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'baseline_optimizer.BaselineOptimizer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
