# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import action_enactor_pb2 as action__enactor__pb2


class ActionEnactorStub(object):
  """The controller service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetThermostatSetpoint = channel.unary_unary(
        '/action_enactor.ActionEnactor/SetThermostatSetpoint',
        request_serializer=action__enactor__pb2.SetpointRequest.SerializeToString,
        response_deserializer=action__enactor__pb2.Response.FromString,
        )
    self.SetThermostatAction = channel.unary_unary(
        '/action_enactor.ActionEnactor/SetThermostatAction',
        request_serializer=action__enactor__pb2.ActionRequest.SerializeToString,
        response_deserializer=action__enactor__pb2.Response.FromString,
        )
    self.SetThermostatOverride = channel.unary_unary(
        '/action_enactor.ActionEnactor/SetThermostatOverride',
        request_serializer=action__enactor__pb2.ThermostatRequest.SerializeToString,
        response_deserializer=action__enactor__pb2.Response.FromString,
        )
    self.SetThermostatOff = channel.unary_unary(
        '/action_enactor.ActionEnactor/SetThermostatOff',
        request_serializer=action__enactor__pb2.ThermostatRequest.SerializeToString,
        response_deserializer=action__enactor__pb2.Response.FromString,
        )
    self.GetThermostatStatus = channel.unary_unary(
        '/action_enactor.ActionEnactor/GetThermostatStatus',
        request_serializer=action__enactor__pb2.StatusRequest.SerializeToString,
        response_deserializer=action__enactor__pb2.Response.FromString,
        )


class ActionEnactorServicer(object):
  """The controller service definition
  """

  def SetThermostatSetpoint(self, request, context):
    """A simple RPC.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetThermostatAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetThermostatOverride(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetThermostatOff(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermostatStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ActionEnactorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetThermostatSetpoint': grpc.unary_unary_rpc_method_handler(
          servicer.SetThermostatSetpoint,
          request_deserializer=action__enactor__pb2.SetpointRequest.FromString,
          response_serializer=action__enactor__pb2.Response.SerializeToString,
      ),
      'SetThermostatAction': grpc.unary_unary_rpc_method_handler(
          servicer.SetThermostatAction,
          request_deserializer=action__enactor__pb2.ActionRequest.FromString,
          response_serializer=action__enactor__pb2.Response.SerializeToString,
      ),
      'SetThermostatOverride': grpc.unary_unary_rpc_method_handler(
          servicer.SetThermostatOverride,
          request_deserializer=action__enactor__pb2.ThermostatRequest.FromString,
          response_serializer=action__enactor__pb2.Response.SerializeToString,
      ),
      'SetThermostatOff': grpc.unary_unary_rpc_method_handler(
          servicer.SetThermostatOff,
          request_deserializer=action__enactor__pb2.ThermostatRequest.FromString,
          response_serializer=action__enactor__pb2.Response.SerializeToString,
      ),
      'GetThermostatStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermostatStatus,
          request_deserializer=action__enactor__pb2.StatusRequest.FromString,
          response_serializer=action__enactor__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'action_enactor.ActionEnactor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
